## making 2D array

In [15]:
import numpy as np
a=np.random.randint(1,20,(3,4))
a

array([[ 4,  9, 12,  4],
       [ 5,  5,  8,  9],
       [ 1, 10, 12, 16]])

In [17]:
boll_arr=a>10
print(boll_arr)

[[False False  True False]
 [False False False False]
 [False False  True  True]]


In [3]:
print(a[boll_arr])

[11 14 14 15 12]


In [18]:
b=a
b

array([[ 4,  9, 12,  4],
       [ 5,  5,  8,  9],
       [ 1, 10, 12, 16]])

In [19]:
b[boll_arr]=100 #updating the satisfied value  #size should be same of a and boll_arr
print(b)

[[  4   9 100   4]
 [  5   5   8   9]
 [  1  10 100 100]]


In [20]:
 # how to check condn on specific row or colum
boll_arr=b[:,3]==100  # check the all row and only 3rd column
print(boll_arr)

[False False  True]
