In [1]:
import numpy as np
a=np.array(['a','b','c','d'])
b=np.random.randint(1,21,8)
print(a)
print(b)

['a' 'b' 'c' 'd']
[ 7  8  5  9  4  9 14  6]


In [10]:
print(b>5) #return boolean value

[ True  True False  True False  True  True  True]


## boolean indexing is helpful get the satisfied value present in array

In [6]:
bool_arr=b>5
print(bool_arr)
new_arr=b[bool_arr] # it only store boolean value which is true
print(new_arr)

[ True  True False  True False  True  True  True]
[ 7  8  9  9 14  6]


In [9]:
# another shortcut method
new_arr=b[b>5]
print(new_arr)

[ 7  8  9  9 14  6]


In [11]:
new_arr=b[(b>5)&(b<16)] # logical operator 
print(new_arr)

[ 7  8  9  9 14  6]


In [14]:
print(b)
c=b

[ 7  8  5  9  4  9 14  6]


In [17]:
c[:3]=19 # this way we can update multiple element in single way
print(c)
c[c>10]=50
print(c)

[19 19 19  9  4  9 50  6]
[50 50 50  9  4  9 50  6]


In [18]:
print(b)

[50 50 50  9  4  9 50  6]


In [21]:
te=np.where(b>4) # return the index of value which satisfied the condn
print(te)
print(b[te]) # to get the satisfied value related to index

(array([0, 1, 2, 3, 5, 6, 7]),)
[50 50 50  9  9 50  6]


## some question


## find the index of non zero element

In [22]:
import numpy as np
li=[1,2,0,0,4,0]
arr=np.array(li)

ind=np.where(arr>0)
print(ind)   #index
print(arr[ind]) # value

(array([0, 1, 4]),)
[1 2 4]


## given a arr size of 10.print the index of element multiple of 3

In [25]:
import numpy as np
li=[1,3,5,7,9,11,13,15,17,19]
arr=np.array(li)

ind=np.where((arr%3)==0)
print(ind) # for index
print(arr[ind])

(array([1, 4, 7]),)
[ 3  9 15]


##  replace the even number from numpy array with -1

In [31]:
import numpy as np
li=[1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10]
arr=np.array(li)
print(arr)

ind=np.where((arr%2)==0)
print(ind)
arr[ind]=-1
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
(array([1, 3, 5, 7, 9]),)
[ 1 -1  3 -1  5 -1  7 -1  9 -1]


# replace the maximum value by 0

In [38]:
import numpy as np
li=[1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10]
arr=np.array(li)
print(arr)

print(arr.max())

ind=arr.argmax()
arr[ind]=0
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
10
[1 2 3 4 5 6 7 8 9 0]


## make negative number whic is between 3 and 8(both inclusive)

In [41]:
import numpy as np
li=[1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,10]
arr=np.array(li)
print(arr)

ind=np.where((arr>=3)&(arr<=8))
print(ind)
arr[ind]=-1
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]
(array([2, 3, 4, 5, 6, 7]),)
[ 1  2 -1 -1 -1 -1 -1 -1  9 10]


In [46]:
import numpy as np
li1=["prasnt","shabaz","jitendra","snehal" ,"sanjay"]
li2=[130,140,160,174,156]
name=np.array(li1)
height=np.array(li2)

ind=np.where(height>155)
print(name[ind])
print(height[ind])

['jitendra' 'snehal' 'sanjay']
[160 174 156]
