## broadcasting is used when we want to do some operation on 2 2D array which size is not same  
## note (m*n| M*N) in one 2D array m|(M) or n|(N) value should be 1

In [1]:
import numpy as np
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a)
print()
print(b)

[[2 3 8]
 [9 6 8]
 [3 7 2]]

[[2 2 9]
 [7 5 5]
 [3 3 9]]


In [2]:
print(a+b) # for equal size of array

[[ 4  5 17]
 [16 11 13]
 [ 6 10 11]]


In [3]:
# for different size
import numpy as np
a=np.random.randint(1,10,(3,3)) # one of m or n sholud be 1
b=np.random.randint(1,10,(3))
print(a)
print()
print(b)

[[2 2 3]
 [7 2 8]
 [9 2 5]]

[6 7 7]


In [4]:
print(a+b)

[[ 8  9 10]
 [13  9 15]
 [15  9 12]]


In [5]:
b=np.random.randint(1,10,(3,4))
b

array([[5, 9, 1, 9],
       [8, 4, 9, 4],
       [8, 9, 6, 8]])

In [6]:
# how to transpose
b=np.transpose(b)
print(b)

[[5 8 8]
 [9 4 9]
 [1 9 6]
 [9 4 8]]


## other function


In [7]:
a=np.array([[0,1],[2,3]])
a

array([[0, 1],
       [2, 3]])

In [8]:
np.resize(a,(2,3)) #resize change into the desire size

array([[0, 1, 2],
       [3, 0, 1]])

In [9]:
np.resize(a,(1,4))

array([[0, 1, 2, 3]])

In [10]:
a = np.arange(6).reshape((3, 2)) # reshape make desire size of array
a


array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
np.reshape(a, (2, 3)) 

array([[0, 1, 2],
       [3, 4, 5]])