In [3]:
import numpy as np
li=[1,2,3,4]
a=np.random.randint(1,20,5)
b=np.random.randint(1,20,5)
print(li)
print(a)
print(b)

[1, 2, 3, 4]
[12  4 13  5 14]
[ 9 14  6  1 19]


## task is to add by 1 in every element

In [4]:
# in list
li=[i+1 for i in li]
print(li)

[2, 3, 4, 5]


In [5]:
# in numpy array
a=a+1
print(a)

[13  5 14  6 15]


## mathematical operation

In [8]:
print(a)
print(b)
print()
c=a+b  # just normal operation 
print(c)
print()
d=a-b
print(d)
print()
e=a*b
print(e)

#/,//,a**b(exponent) 

[13  5 14  6 15]
[ 9 14  6  1 19]

[22 19 20  7 34]

[ 4 -9  8  5 -4]

[117  70  84   6 285]


## some function

In [14]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin()) # return the index of minimum element
print(a.argmax())

[13  5 14  6 15]
53
10.6
5
15
1
4


## logical operation

In [15]:
print(a)
print(b)

[13  5 14  6 15]
[ 9 14  6  1 19]


In [16]:
a>b  #compare the element is same index and return boolean value
# a<b,a==b,a<=b all 

array([ True, False,  True,  True, False])

In [17]:
a<=b

array([False,  True, False, False,  True])

## logical statement

In [20]:
print(np.logical_or(a,b))  # for non zero value it return True
print(np.logical_and(a,b))  

[ True  True  True  True  True]
[ True  True  True  True  True]


In [23]:
a[2]=0
print(a)
print(np.logical_not(a)) # for zero value return True

[13  5  0  6 15]
[False False  True False False]
