## how to create array using numpy

In [2]:
import numpy as np
a=np.arange(10) #default step is one
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
import numpy as np
a=np.arange(2,10,2) 
a

array([2, 4, 6, 8])

In [4]:
import numpy as np
a=np.linspace(2,10) #it will get defalut 50 value which are equally difference(which is set by system)
a

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [5]:
print(a[0]-a[1])
print(a[10]-a[11])

-0.16326530612244916
-0.16326530612244872


In [8]:
import numpy as np
a=np.linspace(2,10,5,dtype=int) # start,end,number of value required # in nature it give float
a   # 10 is enclusive not like range

array([ 2,  4,  6,  8, 10])

## how to print specific number after decimal

In [15]:
import numpy as np
a=np.linspace(0,5,9)
np.set_printoptions(precision=2) # this help to print specific number after decimal
a

array([0.  , 0.62, 1.25, 1.88, 2.5 , 3.12, 3.75, 4.38, 5.  ])

In [9]:
import numpy as np
a=np.linspace(2,10,5,dtype=int,endpoint=False) #this make end value exclude for computation
a

array([2, 3, 5, 6, 8])

## using np.arange() we can control on step value but in np.linspace() we can cantrol on sample value
## in np.arrage() end value is not print but in np.linspace() end value will be print by default

In [10]:
b=np.identity(3) # it will give 3*3 matrix with identity value on diagonal # we can pass only one argument m and it give m*m matrix
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
b=np.identity(5) # it will give 3*3 matrix with identity value on diagonal
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
b=np.eye(3) #same as identity
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
b=np.eye(3,4) #we can pass two argument which is M*N matrix
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
b=np.random.rand(3) # give 3 size of array with random value from range 0-1
b 

array([0.81174099, 0.16419649, 0.82407208])

In [16]:
b=np.random.rand(3)*10 # it will generate random  3 value range from 0-10 using (*10)
b 

array([3.81895194, 7.67254534, 8.56083212])

In [15]:
b=np.random.rand(3,2)  #for 2D matrix
b 

array([[0.27244847, 0.16783609],
       [0.9848628 , 0.43383162],
       [0.25092507, 0.18150491]])

In [19]:
b=np.random.randint(5,size=8)  #where 5 means int value from 0-4 and size=8 means 8 value
b 

array([4, 0, 2, 0, 4, 1, 0, 2])

In [4]:
import numpy as np
b=np.random.randint(5,size=(3,4))  #where 5 means int value and(3,4) means matrix
print(b)

[[0 2 1 0]
 [3 2 4 0]
 [1 0 4 3]]
