# why numpy
## size required for a array for 1 character is 8byte where as size for normal arr is 28 bytes
## (memory requirement is less in numpy)
## numpy array is much faster execute as compare to python normal array 
## numpy array is easy to use 
## numpy library has lot of functionality 

In [5]:
import numpy as np
# no need to import array module because already array module present in numpy
a=[1,2,3,4]
b=np.array(a) #np.array() is a method present in numpy
print(type(a))
print(type(b))


<class 'list'>
<class 'numpy.ndarray'>


In [6]:
import numpy as np
a=[1,2,3,4,'4','str']
b=np.array(a)
print(b) # numpy array support homogeneious data type means same data type

['1' '2' '3' '4' '4' 'str']


In [2]:
import numpy as np
f=[1,2,3,4,'4',6.0]
g=np.array(f,dtype=int)#float,string # this can change only float and number in the form of string
print(g)  

[1 2 3 4 4 6]


In [30]:
import numpy as np
f=[[1,2,3],[4,5,6],[7,8,9]]
g=np.array(f)
print(g)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
import numpy as np
f=[1,2,3,4,'4',6.0]
g=np.array(f*2)
print(g) 

['1' '2' '3' '4' '4' '6.0' '1' '2' '3' '4' '4' '6.0']


## other np method

In [5]:
b=np.ones(3) # in nature if give float value
b

array([1., 1., 1.])

In [6]:
b=np.ones(3,dtype=int) #1d array
b

array([1, 1, 1])

In [9]:
b=np.ones((3,2),dtype=int) #2d array row*column
b

array([[1, 1],
       [1, 1],
       [1, 1]])

In [8]:
b=np.zeros(3,dtype=int)
b

array([0, 0, 0])

In [10]:
b=np.zeros((3,4),dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
b=np.full(3,4) #means 3 column and value is 4 (column_size,value)  #in nature it give int value
b

array([4, 4, 4])

In [12]:
# for 2d array/matrix
b=np.full((3,3),4) 
b

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [27]:
import numpy as np
  
b = np.empty(2,dtype=int)  # array size of 2 with value of random integer
b

array([   0, 2043])

In [29]:
import numpy as np
  
a = np.empty([2, 2],dtype=int) #in nature it is float
a

array([[0, 0],
       [0, 0]])